baseURL = "https://cylllllll.github.io"
# title = "Hugo Themes"
author = "cy"
copyright = "Copyright © 2021, all rights reserved."
paginate = 5
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "cy's Blog 🍉"

[params]
  github = 'cylllllll'
  # instagram = 'cylllllll'
# ------------------------------

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "puzzle"
    name = "puzzle"
    url = "/puzzle/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
